apiVersion: v1
kind: Namespace
metadata:
  name: corporate-intel
  labels:
    app: corporate-intel
    environment: production
    
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: corporate-intel-quota
  namespace: corporate-intel
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "40Gi"
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
    
---
apiVersion: v1
kind: LimitRange
metadata:
  name: corporate-intel-limits
  namespace: corporate-intel
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    type: Container