import React from 'react';
import { Link } from 'react-router-dom';
import { Search, BookOpen, Brain, Play } from 'lucide-react';

const HomePage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      {/* Hero Section */}
      <div className="container mx-auto px-4 py-12">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold text-gray-900 dark:text-white mb-6">
            VocabLens
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto">
            Learn Spanish vocabulary through AI-powered image descriptions. 
            Search, discover, and master new words with visual context.
          </p>
          <Link
            to="/search"
            className="inline-flex items-center px-8 py-4 text-lg font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 transition-colors duration-200 shadow-lg hover:shadow-xl"
          >
            <Search className="w-5 h-5 mr-2" />
            Start Learning
          </Link>
        </div>

        {/* Feature Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-lg hover:shadow-xl transition-shadow duration-200">
            <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center mb-6">
              <Search className="w-6 h-6 text-blue-600 dark:text-blue-400" />
            </div>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
              Search Images
            </h3>
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Discover thousands of high-quality images from Unsplash to practice with real-world visual context.
            </p>
            <Link
              to="/search"
              className="text-blue-600 dark:text-blue-400 font-medium hover:underline"
            >
              Explore Images →
            </Link>
          </div>

          <div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-lg hover:shadow-xl transition-shadow duration-200">
            <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/30 rounded-lg flex items-center justify-center mb-6">
              <Brain className="w-6 h-6 text-purple-600 dark:text-purple-400" />
            </div>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
              AI Descriptions
            </h3>
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Get detailed Spanish descriptions generated by AI, perfect for learning vocabulary in context.
            </p>
            <Link
              to="/search"
              className="text-purple-600 dark:text-purple-400 font-medium hover:underline"
            >
              Try AI Descriptions →
            </Link>
          </div>

          <div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-lg hover:shadow-xl transition-shadow duration-200">
            <div className="w-12 h-12 bg-green-100 dark:bg-green-900/30 rounded-lg flex items-center justify-center mb-6">
              <BookOpen className="w-6 h-6 text-green-600 dark:text-green-400" />
            </div>
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
              Build Vocabulary
            </h3>
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Save interesting words and build your personal Spanish vocabulary collection with spaced repetition.
            </p>
            <Link
              to="/vocabulary"
              className="text-green-600 dark:text-green-400 font-medium hover:underline"
            >
              Manage Words →
            </Link>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="text-center">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-8">
            Quick Start
          </h2>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link
              to="/search?q=nature"
              className="inline-flex items-center px-6 py-3 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors duration-200"
            >
              Search Nature Images
            </Link>
            <Link
              to="/vocabulary"
              className="inline-flex items-center px-6 py-3 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors duration-200"
            >
              View My Words
            </Link>
            <Link
              to="/quiz"
              className="inline-flex items-center px-6 py-3 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700 transition-colors duration-200"
            >
              <Play className="w-4 h-4 mr-2" />
              Practice Quiz
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomePage;
