# VocabLens Netlify Configuration - Emergency Deployment from Root

[build]
  publish = "."
  command = "echo 'Using root directory - build files already copied'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200