# VocabLens Netlify Configuration - Minimal Working Setup

[build]
  publish = "."
  command = "echo 'Using root directory for emergency deployment'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200