# VocabLens Netlify Configuration
# Simplified configuration for reliable deployment

[build]
  # Standard Vite build command
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# SPA routing - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200