# VocabLens Netlify Configuration - Bulletproof Deployment

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200