# Wrangler configuration for Cloudflare Pages
name = "project-workspace"
compatibility_date = "2024-08-29"

# Pages configuration
[env.production]
name = "project-workspace-prod"
compatibility_date = "2024-08-29"
# Custom domain (replace with your actual domain)
# route = "yourdomain.com/*"

[env.staging]
name = "project-workspace-staging"
compatibility_date = "2024-08-29"
# route = "staging.yourdomain.com/*"

[env.preview]
name = "project-workspace-preview"
compatibility_date = "2024-08-29"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables (use wrangler secret put for sensitive values)
[vars]
NODE_ENV = "production"
# Add non-sensitive environment variables here

# KV Namespaces (if needed)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 Databases (if needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "your-database-name"
# database_id = "your-database-id"

# R2 Buckets (if needed for file storage)
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "your-bucket-name"

# Analytics Engine (if needed)
# [analytics_engine_datasets]
# binding = "ANALYTICS"
# dataset = "your-analytics-dataset"

# Custom headers and routing
[wrangler]
send_metrics = false

# Pages functions configuration
[pages]
# Functions directory (if using Cloudflare Pages Functions)
# functions_dir = "functions"

# Asset configuration
[assets]
# Directory containing static assets
directory = "build"
# Include patterns
include = ["**/*"]
# Exclude patterns
exclude = [
  "*.map",
  "*.test.js",
  "*.spec.js",
  "node_modules/**/*",
  ".git/**/*",
  ".svelte-kit/**/*"
]