global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-backend'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'app-frontend'
    static_configs:
      - targets: ['app:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'supabase-db'
    static_configs:
      - targets: ['supabase-db:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093