source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and all whitelisted plugins
gem "github-pages", "~> 232", group: :jekyll_plugins

# Additional plugins (if not included in github-pages)
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby compatibility
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock http_parser.rb gem to v0.6.x on JRuby builds
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# WebP support for image optimization
gem "webrick"